name: nice-slam
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - cudatoolkit=11.3
  - libtiff=4.2.0
  - mkl=2021.4.0
  - numpy=1.21.5
  - matplotlib=3.4.3
  - pillow=9.0.1
  - cmake
  - ninja
  - pyembree
  - pip
  - pip:
      - addict==2.4.0
      - colorama==0.4.4
      - open3d==0.13.0
      - opencv-python==4.5.5.64
      - trimesh==3.10.7
      - scipy==1.7.3
      - scikit-image==0.19.2
      - tqdm==4.63.1
      - pyyaml==6.0
      - gdown==4.4.0
      - mathutils=2.81.2