name: base  # Change name to base for Colab
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - pyembree
  - pip
  - pip:
      - mathutils==2.81.2
      - open3d==0.13.0
      - opencv-python==4.5.5.64
      - trimesh==3.10.7
      - addict==2.4.0
      - tqdm==4.63.1
      - pyyaml==6.0